POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "admin@burger.com",
    "password": "123456"
}

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGJ1cmdlci5jb20iLCJpYXQiOjE2NTUxNjE5NDAsImV4cCI6MTY1NTE2NTU0MCwic3ViIjoiMSJ9.MZfjp8kHpJrJValwzRg8beHtS_380U8bDRg72DaONR0

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhaXRlckBidXJnZXIuY29tIiwiaWF0IjoxNjUzNDI0OTgxLCJleHAiOjE2NTM0Mjg1ODEsInN1YiI6IjIifQ.88l0AOSjz9l6RZGljHDHD4SrorpeRcQ1G5qWywoMkEg

GET http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhaXRlckBidXJnZXIuY29tIiwiaWF0IjoxNjUzNjcwNTQwLCJleHAiOjE2NTM2NzQxNDAsInN1YiI6IjIifQ.SNnl2R9_TM-LA_dRwar7YjmB8KP7FhsRTDfXeApgIlc

PATCH http://localhost:8080/orders/2 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoZWZAYnVyZ2VyLmNvbSIsImlhdCI6MTY1NDYzNzU3MywiZXhwIjoxNjU0NjQxMTczLCJzdWIiOiIzIn0.fEpHUVjF1K08D5tXtPIaRvYTppBddoXcaoVFR3hOnFE

{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}